# coding: utf-8

"""
    Airflow API

    Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.  **Filtering with pattern parameters.** Many list endpoints accept ``*_pattern`` and ``*_prefix_pattern`` query parameters. Unless a parameter's own description says otherwise, ``*_pattern`` is a case-insensitive substring match (SQL ``ILIKE '%term%'``) where ``%`` matches any sequence and ``_`` matches any single character (e.g. ``%customer_%``) — convenient, but it cannot use B-tree indexes, so it is slow on large tables. ``*_prefix_pattern`` matches the start of the value, is case-sensitive and index-friendly (prefer it at scale); there ``%`` and ``_`` are literal and trailing non-alphanumeric characters are stripped so the range scan stays index-compatible under locale-aware collations (e.g. ``test_`` matches values starting with ``test``, and ``s3://`` matches ``s3``). In both, ``|`` means OR (e.g. ``dag1|dag2``) and ``~`` matches everything. Regular expressions are not supported by these parameters; regex-capable endpoints expose a separate parameter.

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from airflow_client.client.models.dag_version_collection_response import DAGVersionCollectionResponse

class TestDAGVersionCollectionResponse(unittest.TestCase):
    """DAGVersionCollectionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DAGVersionCollectionResponse:
        """Test DAGVersionCollectionResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DAGVersionCollectionResponse`
        """
        model = DAGVersionCollectionResponse()
        if include_optional:
            return DAGVersionCollectionResponse(
                dag_versions = [
                    airflow_client.client.models.dag_version_response.DagVersionResponse(
                        bundle_name = '', 
                        bundle_url = '', 
                        bundle_version = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        dag_display_name = '', 
                        dag_id = '', 
                        id = '', 
                        version_number = 56, )
                    ],
                total_entries = 56
            )
        else:
            return DAGVersionCollectionResponse(
                dag_versions = [
                    airflow_client.client.models.dag_version_response.DagVersionResponse(
                        bundle_name = '', 
                        bundle_url = '', 
                        bundle_version = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        dag_display_name = '', 
                        dag_id = '', 
                        id = '', 
                        version_number = 56, )
                    ],
                total_entries = 56,
        )
        """

    def testDAGVersionCollectionResponse(self):
        """Test DAGVersionCollectionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
