# coding: utf-8

"""
    Airflow API

    Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.  **Filtering with pattern parameters.** Many list endpoints accept ``*_pattern`` and ``*_prefix_pattern`` query parameters. Unless a parameter's own description says otherwise, ``*_pattern`` is a case-insensitive substring match (SQL ``ILIKE '%term%'``) where ``%`` matches any sequence and ``_`` matches any single character (e.g. ``%customer_%``) — convenient, but it cannot use B-tree indexes, so it is slow on large tables. ``*_prefix_pattern`` matches the start of the value, is case-sensitive and index-friendly (prefer it at scale); there ``%`` and ``_`` are literal and trailing non-alphanumeric characters are stripped so the range scan stays index-compatible under locale-aware collations (e.g. ``test_`` matches values starting with ``test``, and ``s3://`` matches ``s3``). In both, ``|`` means OR (e.g. ``dag1|dag2``) and ``~`` matches everything. Regular expressions are not supported by these parameters; regex-capable endpoints expose a separate parameter.

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from airflow_client.client.api.dag_run_api import DagRunApi


class TestDagRunApi(unittest.TestCase):
    """DagRunApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DagRunApi()

    def tearDown(self) -> None:
        pass

    def test_bulk_dag_runs(self) -> None:
        """Test case for bulk_dag_runs

        Bulk Dag Runs
        """
        pass

    def test_clear_dag_run(self) -> None:
        """Test case for clear_dag_run

        Clear Dag Run
        """
        pass

    def test_clear_dag_run_partitions(self) -> None:
        """Test case for clear_dag_run_partitions

        Clear Dag Run Partitions
        """
        pass

    def test_clear_dag_runs(self) -> None:
        """Test case for clear_dag_runs

        Clear Dag Runs
        """
        pass

    def test_delete_dag_run(self) -> None:
        """Test case for delete_dag_run

        Delete Dag Run
        """
        pass

    def test_get_dag_run(self) -> None:
        """Test case for get_dag_run

        Get Dag Run
        """
        pass

    def test_get_dag_runs(self) -> None:
        """Test case for get_dag_runs

        Get Dag Runs
        """
        pass

    def test_get_list_dag_runs_batch(self) -> None:
        """Test case for get_list_dag_runs_batch

        Get List Dag Runs Batch
        """
        pass

    def test_get_upstream_asset_events(self) -> None:
        """Test case for get_upstream_asset_events

        Get Upstream Asset Events
        """
        pass

    def test_patch_dag_run(self) -> None:
        """Test case for patch_dag_run

        Patch Dag Run
        """
        pass

    def test_trigger_dag_run(self) -> None:
        """Test case for trigger_dag_run

        Trigger Dag Run
        """
        pass

    def test_wait_dag_run_until_finished(self) -> None:
        """Test case for wait_dag_run_until_finished

        Experimental: Wait for a dag run to complete, and return task results if requested.
        """
        pass


if __name__ == '__main__':
    unittest.main()
