# coding: utf-8

"""
    Airflow API

    Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from airflow_client.client.models.dag_run_collection_response import DAGRunCollectionResponse

class TestDAGRunCollectionResponse(unittest.TestCase):
    """DAGRunCollectionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DAGRunCollectionResponse:
        """Test DAGRunCollectionResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DAGRunCollectionResponse`
        """
        model = DAGRunCollectionResponse()
        if include_optional:
            return DAGRunCollectionResponse(
                dag_runs = [
                    airflow_client.client.models.dag_run_response.DAGRunResponse(
                        bundle_version = '', 
                        conf = airflow_client.client.models.conf.Conf(), 
                        dag_id = '', 
                        dag_run_id = '', 
                        dag_versions = [
                            airflow_client.client.models.dag_version_response.DagVersionResponse(
                                bundle_name = '', 
                                bundle_url = '', 
                                bundle_version = '', 
                                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                dag_id = '', 
                                id = '', 
                                version_number = 56, )
                            ], 
                        data_interval_end = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        data_interval_start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        last_scheduling_decision = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        logical_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        note = '', 
                        queued_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        run_after = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        run_type = 'backfill', 
                        start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        state = 'queued', 
                        triggered_by = 'cli', )
                    ],
                total_entries = 56
            )
        else:
            return DAGRunCollectionResponse(
                dag_runs = [
                    airflow_client.client.models.dag_run_response.DAGRunResponse(
                        bundle_version = '', 
                        conf = airflow_client.client.models.conf.Conf(), 
                        dag_id = '', 
                        dag_run_id = '', 
                        dag_versions = [
                            airflow_client.client.models.dag_version_response.DagVersionResponse(
                                bundle_name = '', 
                                bundle_url = '', 
                                bundle_version = '', 
                                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                dag_id = '', 
                                id = '', 
                                version_number = 56, )
                            ], 
                        data_interval_end = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        data_interval_start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        last_scheduling_decision = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        logical_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        note = '', 
                        queued_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        run_after = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        run_type = 'backfill', 
                        start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        state = 'queued', 
                        triggered_by = 'cli', )
                    ],
                total_entries = 56,
        )
        """

    def testDAGRunCollectionResponse(self):
        """Test DAGRunCollectionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
