# coding: utf-8

"""
    Airflow API

    Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from airflow_client.client.models.task_instances_inner import TaskInstancesInner

class TestTaskInstancesInner(unittest.TestCase):
    """TaskInstancesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaskInstancesInner:
        """Test TaskInstancesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaskInstancesInner`
        """
        model = TaskInstancesInner()
        if include_optional:
            return TaskInstancesInner(
                id = '',
                task_id = '',
                dag_id = '',
                dag_run_id = '',
                map_index = 56,
                logical_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                run_after = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                duration = 1.337,
                state = 'removed',
                try_number = 56,
                max_tries = 56,
                task_display_name = '',
                dag_display_name = '',
                hostname = '',
                unixname = '',
                pool = '',
                pool_slots = 56,
                queue = '',
                priority_weight = 56,
                operator = '',
                operator_name = '',
                queued_when = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                scheduled_when = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                pid = 56,
                executor = '',
                executor_config = '',
                note = '',
                rendered_map_index = '',
                rendered_fields = { },
                trigger = airflow_client.client.models.trigger_response.TriggerResponse(
                    id = 56, 
                    classpath = '', 
                    kwargs = '', 
                    created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    queue = '', 
                    triggerer_id = 56, ),
                triggerer_job = airflow_client.client.models.job_response.JobResponse(
                    id = 56, 
                    dag_id = '', 
                    state = '', 
                    job_type = '', 
                    start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    latest_heartbeat = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    executor_class = '', 
                    hostname = '', 
                    unixname = '', 
                    dag_display_name = '', ),
                dag_version = airflow_client.client.models.dag_version_response.DagVersionResponse(
                    id = '', 
                    version_number = 56, 
                    dag_id = '', 
                    bundle_name = '', 
                    bundle_version = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    dag_display_name = '', 
                    bundle_url = '', )
            )
        else:
            return TaskInstancesInner(
                id = '',
                task_id = '',
                dag_id = '',
                dag_run_id = '',
                map_index = 56,
                logical_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                run_after = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                duration = 1.337,
                state = 'removed',
                try_number = 56,
                max_tries = 56,
                task_display_name = '',
                dag_display_name = '',
                hostname = '',
                unixname = '',
                pool = '',
                pool_slots = 56,
                queue = '',
                priority_weight = 56,
                operator = '',
                operator_name = '',
                queued_when = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                scheduled_when = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                pid = 56,
                executor = '',
                executor_config = '',
                note = '',
                rendered_map_index = '',
                trigger = airflow_client.client.models.trigger_response.TriggerResponse(
                    id = 56, 
                    classpath = '', 
                    kwargs = '', 
                    created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    queue = '', 
                    triggerer_id = 56, ),
                triggerer_job = airflow_client.client.models.job_response.JobResponse(
                    id = 56, 
                    dag_id = '', 
                    state = '', 
                    job_type = '', 
                    start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    latest_heartbeat = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    executor_class = '', 
                    hostname = '', 
                    unixname = '', 
                    dag_display_name = '', ),
                dag_version = airflow_client.client.models.dag_version_response.DagVersionResponse(
                    id = '', 
                    version_number = 56, 
                    dag_id = '', 
                    bundle_name = '', 
                    bundle_version = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    dag_display_name = '', 
                    bundle_url = '', ),
        )
        """

    def testTaskInstancesInner(self):
        """Test TaskInstancesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
