# coding: utf-8

"""
    Airflow API

    Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from airflow_client.client.api.x_com_api import XComApi


class TestXComApi(unittest.TestCase):
    """XComApi unit test stubs"""

    def setUp(self) -> None:
        self.api = XComApi()

    def tearDown(self) -> None:
        pass

    def test_create_xcom_entry(self) -> None:
        """Test case for create_xcom_entry

        Create Xcom Entry
        """
        pass

    def test_get_xcom_entries(self) -> None:
        """Test case for get_xcom_entries

        Get Xcom Entries
        """
        pass

    def test_get_xcom_entry(self) -> None:
        """Test case for get_xcom_entry

        Get Xcom Entry
        """
        pass

    def test_update_xcom_entry(self) -> None:
        """Test case for update_xcom_entry

        Update Xcom Entry
        """
        pass


if __name__ == '__main__':
    unittest.main()
