# coding: utf-8

"""
    Airflow API

    Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.  **Filtering with pattern parameters.** Many list endpoints accept ``*_pattern`` and ``*_prefix_pattern`` query parameters. Unless a parameter's own description says otherwise, ``*_pattern`` is a case-insensitive substring match (SQL ``ILIKE '%term%'``) where ``%`` matches any sequence and ``_`` matches any single character (e.g. ``%customer_%``) — convenient, but it cannot use B-tree indexes, so it is slow on large tables. ``*_prefix_pattern`` matches the start of the value, is case-sensitive and index-friendly (prefer it at scale); there ``%`` and ``_`` are literal and trailing non-alphanumeric characters are stripped so the range scan stays index-compatible under locale-aware collations (e.g. ``test_`` matches values starting with ``test``, and ``s3://`` matches ``s3``). In both, ``|`` means OR (e.g. ``dag1|dag2``) and ``~`` matches everything. Regular expressions are not supported by these parameters; regex-capable endpoints expose a separate parameter.

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from airflow_client.client.api.backfill_api import BackfillApi


class TestBackfillApi(unittest.TestCase):
    """BackfillApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BackfillApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_backfill(self) -> None:
        """Test case for cancel_backfill

        Cancel Backfill
        """
        pass

    def test_create_backfill(self) -> None:
        """Test case for create_backfill

        Create Backfill
        """
        pass

    def test_create_backfill_dry_run(self) -> None:
        """Test case for create_backfill_dry_run

        Create Backfill Dry Run
        """
        pass

    def test_get_backfill(self) -> None:
        """Test case for get_backfill

        Get Backfill
        """
        pass

    def test_list_backfills(self) -> None:
        """Test case for list_backfills

        List Backfills
        """
        pass

    def test_pause_backfill(self) -> None:
        """Test case for pause_backfill

        Pause Backfill
        """
        pass

    def test_unpause_backfill(self) -> None:
        """Test case for unpause_backfill

        Unpause Backfill
        """
        pass


if __name__ == '__main__':
    unittest.main()
