# coding: utf-8

"""
    Airflow API

    Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from airflow_client.client.models.reprocess_behavior import ReprocessBehavior
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BackfillResponse(BaseModel):
    """
    Base serializer for Backfill.
    """ # noqa: E501
    id: Annotated[int, Field(strict=True, ge=0)]
    dag_id: StrictStr
    from_date: datetime
    to_date: datetime
    dag_run_conf: Optional[Dict[str, Any]]
    is_paused: StrictBool
    reprocess_behavior: ReprocessBehavior
    max_active_runs: StrictInt
    created_at: datetime
    completed_at: Optional[datetime]
    updated_at: datetime
    dag_display_name: StrictStr
    __properties: ClassVar[List[str]] = ["id", "dag_id", "from_date", "to_date", "dag_run_conf", "is_paused", "reprocess_behavior", "max_active_runs", "created_at", "completed_at", "updated_at", "dag_display_name"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BackfillResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if dag_run_conf (nullable) is None
        # and model_fields_set contains the field
        if self.dag_run_conf is None and "dag_run_conf" in self.model_fields_set:
            _dict['dag_run_conf'] = None

        # set to None if completed_at (nullable) is None
        # and model_fields_set contains the field
        if self.completed_at is None and "completed_at" in self.model_fields_set:
            _dict['completed_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BackfillResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "dag_id": obj.get("dag_id"),
            "from_date": obj.get("from_date"),
            "to_date": obj.get("to_date"),
            "dag_run_conf": obj.get("dag_run_conf"),
            "is_paused": obj.get("is_paused"),
            "reprocess_behavior": obj.get("reprocess_behavior"),
            "max_active_runs": obj.get("max_active_runs"),
            "created_at": obj.get("created_at"),
            "completed_at": obj.get("completed_at"),
            "updated_at": obj.get("updated_at"),
            "dag_display_name": obj.get("dag_display_name")
        })
        return _obj


