# coding: utf-8

"""
    Airflow API

    Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from airflow_client.client.models.bulk_dag_run_body import BulkDAGRunBody
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BulkDAGRunClearBody(BaseModel):
    """
    Request body for the bulk clear Dag Runs endpoint.
    """ # noqa: E501
    dag_runs: Optional[List[BulkDAGRunBody]] = None
    dry_run: Optional[StrictBool] = True
    note: Optional[Annotated[str, Field(strict=True, max_length=1000)]] = None
    only_failed: Optional[StrictBool] = False
    only_new: Optional[StrictBool] = Field(default=False, description="Only queue newly added tasks in the latest Dag version without clearing existing tasks.")
    partition_date_end: Optional[datetime] = None
    partition_date_start: Optional[datetime] = None
    partition_key: Optional[StrictStr] = None
    run_on_latest_version: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["dag_runs", "dry_run", "note", "only_failed", "only_new", "partition_date_end", "partition_date_start", "partition_key", "run_on_latest_version"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BulkDAGRunClearBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in dag_runs (list)
        _items = []
        if self.dag_runs:
            for _item_dag_runs in self.dag_runs:
                if _item_dag_runs:
                    _items.append(_item_dag_runs.to_dict())
            _dict['dag_runs'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BulkDAGRunClearBody from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "dag_runs": [BulkDAGRunBody.from_dict(_item) for _item in obj["dag_runs"]] if obj.get("dag_runs") is not None else None,
            "dry_run": obj.get("dry_run") if obj.get("dry_run") is not None else True,
            "note": obj.get("note"),
            "only_failed": obj.get("only_failed") if obj.get("only_failed") is not None else False,
            "only_new": obj.get("only_new") if obj.get("only_new") is not None else False,
            "partition_date_end": obj.get("partition_date_end"),
            "partition_date_start": obj.get("partition_date_start"),
            "partition_key": obj.get("partition_key"),
            "run_on_latest_version": obj.get("run_on_latest_version")
        })
        return _obj


