# coding: utf-8

"""
    Airflow API

    Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from airflow_client.client.models.clear_task_instances_body_task_ids_inner import ClearTaskInstancesBodyTaskIdsInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ClearTaskInstancesBody(BaseModel):
    """
    Request body for Clear Task Instances endpoint.
    """ # noqa: E501
    dry_run: Optional[StrictBool] = True
    start_date: Optional[datetime] = None
    end_date: Optional[datetime] = None
    only_failed: Optional[StrictBool] = True
    only_running: Optional[StrictBool] = False
    reset_dag_runs: Optional[StrictBool] = True
    task_ids: Optional[List[ClearTaskInstancesBodyTaskIdsInner]] = Field(default=None, description="A list of `task_id` or [`task_id`, `map_index`]. If only the `task_id` is provided for a mapped task, all of its map indices will be targeted.")
    dag_run_id: Optional[StrictStr] = None
    include_upstream: Optional[StrictBool] = False
    include_downstream: Optional[StrictBool] = False
    include_future: Optional[StrictBool] = False
    include_past: Optional[StrictBool] = False
    run_on_latest_version: Optional[StrictBool] = Field(default=False, description="(Experimental) Run on the latest bundle version of the dag after clearing the task instances.")
    prevent_running_task: Optional[StrictBool] = False
    __properties: ClassVar[List[str]] = ["dry_run", "start_date", "end_date", "only_failed", "only_running", "reset_dag_runs", "task_ids", "dag_run_id", "include_upstream", "include_downstream", "include_future", "include_past", "run_on_latest_version", "prevent_running_task"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ClearTaskInstancesBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in task_ids (list)
        _items = []
        if self.task_ids:
            for _item_task_ids in self.task_ids:
                if _item_task_ids:
                    _items.append(_item_task_ids.to_dict())
            _dict['task_ids'] = _items
        # set to None if start_date (nullable) is None
        # and model_fields_set contains the field
        if self.start_date is None and "start_date" in self.model_fields_set:
            _dict['start_date'] = None

        # set to None if end_date (nullable) is None
        # and model_fields_set contains the field
        if self.end_date is None and "end_date" in self.model_fields_set:
            _dict['end_date'] = None

        # set to None if task_ids (nullable) is None
        # and model_fields_set contains the field
        if self.task_ids is None and "task_ids" in self.model_fields_set:
            _dict['task_ids'] = None

        # set to None if dag_run_id (nullable) is None
        # and model_fields_set contains the field
        if self.dag_run_id is None and "dag_run_id" in self.model_fields_set:
            _dict['dag_run_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ClearTaskInstancesBody from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "dry_run": obj.get("dry_run") if obj.get("dry_run") is not None else True,
            "start_date": obj.get("start_date"),
            "end_date": obj.get("end_date"),
            "only_failed": obj.get("only_failed") if obj.get("only_failed") is not None else True,
            "only_running": obj.get("only_running") if obj.get("only_running") is not None else False,
            "reset_dag_runs": obj.get("reset_dag_runs") if obj.get("reset_dag_runs") is not None else True,
            "task_ids": [ClearTaskInstancesBodyTaskIdsInner.from_dict(_item) for _item in obj["task_ids"]] if obj.get("task_ids") is not None else None,
            "dag_run_id": obj.get("dag_run_id"),
            "include_upstream": obj.get("include_upstream") if obj.get("include_upstream") is not None else False,
            "include_downstream": obj.get("include_downstream") if obj.get("include_downstream") is not None else False,
            "include_future": obj.get("include_future") if obj.get("include_future") is not None else False,
            "include_past": obj.get("include_past") if obj.get("include_past") is not None else False,
            "run_on_latest_version": obj.get("run_on_latest_version") if obj.get("run_on_latest_version") is not None else False,
            "prevent_running_task": obj.get("prevent_running_task") if obj.get("prevent_running_task") is not None else False
        })
        return _obj


