# coding: utf-8

"""
    Airflow API

    Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from airflow_client.client.models.dag_run_state import DagRunState
from airflow_client.client.models.dag_run_triggered_by_type import DagRunTriggeredByType
from airflow_client.client.models.dag_run_type import DagRunType
from airflow_client.client.models.dag_version_response import DagVersionResponse
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DAGRunResponse(BaseModel):
    """
    Dag Run serializer for responses.
    """ # noqa: E501
    dag_run_id: StrictStr
    dag_id: StrictStr
    logical_date: Optional[datetime]
    queued_at: Optional[datetime]
    start_date: Optional[datetime]
    end_date: Optional[datetime]
    duration: Optional[Union[StrictFloat, StrictInt]]
    data_interval_start: Optional[datetime]
    data_interval_end: Optional[datetime]
    run_after: datetime
    last_scheduling_decision: Optional[datetime]
    run_type: DagRunType
    state: DagRunState
    triggered_by: Optional[DagRunTriggeredByType]
    triggering_user_name: Optional[StrictStr]
    conf: Optional[Dict[str, Any]]
    note: Optional[StrictStr]
    dag_versions: List[DagVersionResponse]
    bundle_version: Optional[StrictStr]
    dag_display_name: StrictStr
    partition_key: Optional[StrictStr]
    __properties: ClassVar[List[str]] = ["dag_run_id", "dag_id", "logical_date", "queued_at", "start_date", "end_date", "duration", "data_interval_start", "data_interval_end", "run_after", "last_scheduling_decision", "run_type", "state", "triggered_by", "triggering_user_name", "conf", "note", "dag_versions", "bundle_version", "dag_display_name", "partition_key"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DAGRunResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in dag_versions (list)
        _items = []
        if self.dag_versions:
            for _item_dag_versions in self.dag_versions:
                if _item_dag_versions:
                    _items.append(_item_dag_versions.to_dict())
            _dict['dag_versions'] = _items
        # set to None if logical_date (nullable) is None
        # and model_fields_set contains the field
        if self.logical_date is None and "logical_date" in self.model_fields_set:
            _dict['logical_date'] = None

        # set to None if queued_at (nullable) is None
        # and model_fields_set contains the field
        if self.queued_at is None and "queued_at" in self.model_fields_set:
            _dict['queued_at'] = None

        # set to None if start_date (nullable) is None
        # and model_fields_set contains the field
        if self.start_date is None and "start_date" in self.model_fields_set:
            _dict['start_date'] = None

        # set to None if end_date (nullable) is None
        # and model_fields_set contains the field
        if self.end_date is None and "end_date" in self.model_fields_set:
            _dict['end_date'] = None

        # set to None if duration (nullable) is None
        # and model_fields_set contains the field
        if self.duration is None and "duration" in self.model_fields_set:
            _dict['duration'] = None

        # set to None if data_interval_start (nullable) is None
        # and model_fields_set contains the field
        if self.data_interval_start is None and "data_interval_start" in self.model_fields_set:
            _dict['data_interval_start'] = None

        # set to None if data_interval_end (nullable) is None
        # and model_fields_set contains the field
        if self.data_interval_end is None and "data_interval_end" in self.model_fields_set:
            _dict['data_interval_end'] = None

        # set to None if last_scheduling_decision (nullable) is None
        # and model_fields_set contains the field
        if self.last_scheduling_decision is None and "last_scheduling_decision" in self.model_fields_set:
            _dict['last_scheduling_decision'] = None

        # set to None if triggered_by (nullable) is None
        # and model_fields_set contains the field
        if self.triggered_by is None and "triggered_by" in self.model_fields_set:
            _dict['triggered_by'] = None

        # set to None if triggering_user_name (nullable) is None
        # and model_fields_set contains the field
        if self.triggering_user_name is None and "triggering_user_name" in self.model_fields_set:
            _dict['triggering_user_name'] = None

        # set to None if conf (nullable) is None
        # and model_fields_set contains the field
        if self.conf is None and "conf" in self.model_fields_set:
            _dict['conf'] = None

        # set to None if note (nullable) is None
        # and model_fields_set contains the field
        if self.note is None and "note" in self.model_fields_set:
            _dict['note'] = None

        # set to None if bundle_version (nullable) is None
        # and model_fields_set contains the field
        if self.bundle_version is None and "bundle_version" in self.model_fields_set:
            _dict['bundle_version'] = None

        # set to None if partition_key (nullable) is None
        # and model_fields_set contains the field
        if self.partition_key is None and "partition_key" in self.model_fields_set:
            _dict['partition_key'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DAGRunResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "dag_run_id": obj.get("dag_run_id"),
            "dag_id": obj.get("dag_id"),
            "logical_date": obj.get("logical_date"),
            "queued_at": obj.get("queued_at"),
            "start_date": obj.get("start_date"),
            "end_date": obj.get("end_date"),
            "duration": obj.get("duration"),
            "data_interval_start": obj.get("data_interval_start"),
            "data_interval_end": obj.get("data_interval_end"),
            "run_after": obj.get("run_after"),
            "last_scheduling_decision": obj.get("last_scheduling_decision"),
            "run_type": obj.get("run_type"),
            "state": obj.get("state"),
            "triggered_by": obj.get("triggered_by"),
            "triggering_user_name": obj.get("triggering_user_name"),
            "conf": obj.get("conf"),
            "note": obj.get("note"),
            "dag_versions": [DagVersionResponse.from_dict(_item) for _item in obj["dag_versions"]] if obj.get("dag_versions") is not None else None,
            "bundle_version": obj.get("bundle_version"),
            "dag_display_name": obj.get("dag_display_name"),
            "partition_key": obj.get("partition_key")
        })
        return _obj


