# coding: utf-8

"""
    Airflow API

    Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from airflow_client.client.models.dag_run_state import DagRunState
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DAGRunsBatchBody(BaseModel):
    """
    List Dag Runs body for batch endpoint.
    """ # noqa: E501
    order_by: Optional[StrictStr] = None
    page_offset: Optional[Annotated[int, Field(strict=True, ge=0)]] = 0
    page_limit: Optional[Annotated[int, Field(strict=True, ge=0)]] = 100
    dag_ids: Optional[List[StrictStr]] = None
    states: Optional[List[Optional[DagRunState]]] = None
    run_after_gte: Optional[datetime] = None
    run_after_gt: Optional[datetime] = None
    run_after_lte: Optional[datetime] = None
    run_after_lt: Optional[datetime] = None
    logical_date_gte: Optional[datetime] = None
    logical_date_gt: Optional[datetime] = None
    logical_date_lte: Optional[datetime] = None
    logical_date_lt: Optional[datetime] = None
    start_date_gte: Optional[datetime] = None
    start_date_gt: Optional[datetime] = None
    start_date_lte: Optional[datetime] = None
    start_date_lt: Optional[datetime] = None
    end_date_gte: Optional[datetime] = None
    end_date_gt: Optional[datetime] = None
    end_date_lte: Optional[datetime] = None
    end_date_lt: Optional[datetime] = None
    duration_gte: Optional[Union[StrictFloat, StrictInt]] = None
    duration_gt: Optional[Union[StrictFloat, StrictInt]] = None
    duration_lte: Optional[Union[StrictFloat, StrictInt]] = None
    duration_lt: Optional[Union[StrictFloat, StrictInt]] = None
    conf_contains: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["order_by", "page_offset", "page_limit", "dag_ids", "states", "run_after_gte", "run_after_gt", "run_after_lte", "run_after_lt", "logical_date_gte", "logical_date_gt", "logical_date_lte", "logical_date_lt", "start_date_gte", "start_date_gt", "start_date_lte", "start_date_lt", "end_date_gte", "end_date_gt", "end_date_lte", "end_date_lt", "duration_gte", "duration_gt", "duration_lte", "duration_lt", "conf_contains"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DAGRunsBatchBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if order_by (nullable) is None
        # and model_fields_set contains the field
        if self.order_by is None and "order_by" in self.model_fields_set:
            _dict['order_by'] = None

        # set to None if dag_ids (nullable) is None
        # and model_fields_set contains the field
        if self.dag_ids is None and "dag_ids" in self.model_fields_set:
            _dict['dag_ids'] = None

        # set to None if states (nullable) is None
        # and model_fields_set contains the field
        if self.states is None and "states" in self.model_fields_set:
            _dict['states'] = None

        # set to None if run_after_gte (nullable) is None
        # and model_fields_set contains the field
        if self.run_after_gte is None and "run_after_gte" in self.model_fields_set:
            _dict['run_after_gte'] = None

        # set to None if run_after_gt (nullable) is None
        # and model_fields_set contains the field
        if self.run_after_gt is None and "run_after_gt" in self.model_fields_set:
            _dict['run_after_gt'] = None

        # set to None if run_after_lte (nullable) is None
        # and model_fields_set contains the field
        if self.run_after_lte is None and "run_after_lte" in self.model_fields_set:
            _dict['run_after_lte'] = None

        # set to None if run_after_lt (nullable) is None
        # and model_fields_set contains the field
        if self.run_after_lt is None and "run_after_lt" in self.model_fields_set:
            _dict['run_after_lt'] = None

        # set to None if logical_date_gte (nullable) is None
        # and model_fields_set contains the field
        if self.logical_date_gte is None and "logical_date_gte" in self.model_fields_set:
            _dict['logical_date_gte'] = None

        # set to None if logical_date_gt (nullable) is None
        # and model_fields_set contains the field
        if self.logical_date_gt is None and "logical_date_gt" in self.model_fields_set:
            _dict['logical_date_gt'] = None

        # set to None if logical_date_lte (nullable) is None
        # and model_fields_set contains the field
        if self.logical_date_lte is None and "logical_date_lte" in self.model_fields_set:
            _dict['logical_date_lte'] = None

        # set to None if logical_date_lt (nullable) is None
        # and model_fields_set contains the field
        if self.logical_date_lt is None and "logical_date_lt" in self.model_fields_set:
            _dict['logical_date_lt'] = None

        # set to None if start_date_gte (nullable) is None
        # and model_fields_set contains the field
        if self.start_date_gte is None and "start_date_gte" in self.model_fields_set:
            _dict['start_date_gte'] = None

        # set to None if start_date_gt (nullable) is None
        # and model_fields_set contains the field
        if self.start_date_gt is None and "start_date_gt" in self.model_fields_set:
            _dict['start_date_gt'] = None

        # set to None if start_date_lte (nullable) is None
        # and model_fields_set contains the field
        if self.start_date_lte is None and "start_date_lte" in self.model_fields_set:
            _dict['start_date_lte'] = None

        # set to None if start_date_lt (nullable) is None
        # and model_fields_set contains the field
        if self.start_date_lt is None and "start_date_lt" in self.model_fields_set:
            _dict['start_date_lt'] = None

        # set to None if end_date_gte (nullable) is None
        # and model_fields_set contains the field
        if self.end_date_gte is None and "end_date_gte" in self.model_fields_set:
            _dict['end_date_gte'] = None

        # set to None if end_date_gt (nullable) is None
        # and model_fields_set contains the field
        if self.end_date_gt is None and "end_date_gt" in self.model_fields_set:
            _dict['end_date_gt'] = None

        # set to None if end_date_lte (nullable) is None
        # and model_fields_set contains the field
        if self.end_date_lte is None and "end_date_lte" in self.model_fields_set:
            _dict['end_date_lte'] = None

        # set to None if end_date_lt (nullable) is None
        # and model_fields_set contains the field
        if self.end_date_lt is None and "end_date_lt" in self.model_fields_set:
            _dict['end_date_lt'] = None

        # set to None if duration_gte (nullable) is None
        # and model_fields_set contains the field
        if self.duration_gte is None and "duration_gte" in self.model_fields_set:
            _dict['duration_gte'] = None

        # set to None if duration_gt (nullable) is None
        # and model_fields_set contains the field
        if self.duration_gt is None and "duration_gt" in self.model_fields_set:
            _dict['duration_gt'] = None

        # set to None if duration_lte (nullable) is None
        # and model_fields_set contains the field
        if self.duration_lte is None and "duration_lte" in self.model_fields_set:
            _dict['duration_lte'] = None

        # set to None if duration_lt (nullable) is None
        # and model_fields_set contains the field
        if self.duration_lt is None and "duration_lt" in self.model_fields_set:
            _dict['duration_lt'] = None

        # set to None if conf_contains (nullable) is None
        # and model_fields_set contains the field
        if self.conf_contains is None and "conf_contains" in self.model_fields_set:
            _dict['conf_contains'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DAGRunsBatchBody from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "order_by": obj.get("order_by"),
            "page_offset": obj.get("page_offset") if obj.get("page_offset") is not None else 0,
            "page_limit": obj.get("page_limit") if obj.get("page_limit") is not None else 100,
            "dag_ids": obj.get("dag_ids"),
            "states": obj.get("states"),
            "run_after_gte": obj.get("run_after_gte"),
            "run_after_gt": obj.get("run_after_gt"),
            "run_after_lte": obj.get("run_after_lte"),
            "run_after_lt": obj.get("run_after_lt"),
            "logical_date_gte": obj.get("logical_date_gte"),
            "logical_date_gt": obj.get("logical_date_gt"),
            "logical_date_lte": obj.get("logical_date_lte"),
            "logical_date_lt": obj.get("logical_date_lt"),
            "start_date_gte": obj.get("start_date_gte"),
            "start_date_gt": obj.get("start_date_gt"),
            "start_date_lte": obj.get("start_date_lte"),
            "start_date_lt": obj.get("start_date_lt"),
            "end_date_gte": obj.get("end_date_gte"),
            "end_date_gt": obj.get("end_date_gt"),
            "end_date_lte": obj.get("end_date_lte"),
            "end_date_lt": obj.get("end_date_lt"),
            "duration_gte": obj.get("duration_gte"),
            "duration_gt": obj.get("duration_gt"),
            "duration_lte": obj.get("duration_lte"),
            "duration_lt": obj.get("duration_lt"),
            "conf_contains": obj.get("conf_contains")
        })
        return _obj


