# coding: utf-8

"""
    Airflow API

    Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DagRunAssetReference(BaseModel):
    """
    DagRun serializer for asset responses.
    """ # noqa: E501
    run_id: StrictStr
    dag_id: StrictStr
    logical_date: Optional[datetime]
    start_date: datetime
    end_date: Optional[datetime]
    state: StrictStr
    data_interval_start: Optional[datetime]
    data_interval_end: Optional[datetime]
    partition_key: Optional[StrictStr]
    __properties: ClassVar[List[str]] = ["run_id", "dag_id", "logical_date", "start_date", "end_date", "state", "data_interval_start", "data_interval_end", "partition_key"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DagRunAssetReference from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if logical_date (nullable) is None
        # and model_fields_set contains the field
        if self.logical_date is None and "logical_date" in self.model_fields_set:
            _dict['logical_date'] = None

        # set to None if end_date (nullable) is None
        # and model_fields_set contains the field
        if self.end_date is None and "end_date" in self.model_fields_set:
            _dict['end_date'] = None

        # set to None if data_interval_start (nullable) is None
        # and model_fields_set contains the field
        if self.data_interval_start is None and "data_interval_start" in self.model_fields_set:
            _dict['data_interval_start'] = None

        # set to None if data_interval_end (nullable) is None
        # and model_fields_set contains the field
        if self.data_interval_end is None and "data_interval_end" in self.model_fields_set:
            _dict['data_interval_end'] = None

        # set to None if partition_key (nullable) is None
        # and model_fields_set contains the field
        if self.partition_key is None and "partition_key" in self.model_fields_set:
            _dict['partition_key'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DagRunAssetReference from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "run_id": obj.get("run_id"),
            "dag_id": obj.get("dag_id"),
            "logical_date": obj.get("logical_date"),
            "start_date": obj.get("start_date"),
            "end_date": obj.get("end_date"),
            "state": obj.get("state"),
            "data_interval_start": obj.get("data_interval_start"),
            "data_interval_end": obj.get("data_interval_end"),
            "partition_key": obj.get("partition_key")
        })
        return _obj


