# coding: utf-8

"""
    Airflow API

    Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from airflow_client.client.models.extra_links_value import ExtraLinksValue
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ExtraLinkCollectionResponse(BaseModel):
    """
    Extra Links Response.
    """ # noqa: E501
    extra_links: Dict[str, Optional[ExtraLinksValue]]
    total_entries: StrictInt
    __properties: ClassVar[List[str]] = ["extra_links", "total_entries"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExtraLinkCollectionResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in extra_links (dict)
        _field_dict = {}
        if self.extra_links:
            for _key_extra_links in self.extra_links:
                if self.extra_links[_key_extra_links]:
                    _field_dict[_key_extra_links] = self.extra_links[_key_extra_links].to_dict()
            _dict['extra_links'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExtraLinkCollectionResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "extra_links": dict(
                (_k, ExtraLinksValue.from_dict(_v))
                for _k, _v in obj["extra_links"].items()
            )
            if obj.get("extra_links") is not None
            else None,
            "total_entries": obj.get("total_entries")
        })
        return _obj


