# coding: utf-8

"""
    Airflow API

    Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class XComResponseNative(BaseModel):
    """
    XCom response serializer with native return type.
    """ # noqa: E501
    key: StrictStr
    timestamp: datetime
    logical_date: Optional[datetime]
    map_index: StrictInt
    task_id: StrictStr
    dag_id: StrictStr
    run_id: StrictStr
    dag_display_name: StrictStr
    task_display_name: StrictStr
    run_after: datetime
    value: Optional[Any]
    __properties: ClassVar[List[str]] = ["key", "timestamp", "logical_date", "map_index", "task_id", "dag_id", "run_id", "dag_display_name", "task_display_name", "run_after", "value"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of XComResponseNative from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if logical_date (nullable) is None
        # and model_fields_set contains the field
        if self.logical_date is None and "logical_date" in self.model_fields_set:
            _dict['logical_date'] = None

        # set to None if value (nullable) is None
        # and model_fields_set contains the field
        if self.value is None and "value" in self.model_fields_set:
            _dict['value'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of XComResponseNative from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "key": obj.get("key"),
            "timestamp": obj.get("timestamp"),
            "logical_date": obj.get("logical_date"),
            "map_index": obj.get("map_index"),
            "task_id": obj.get("task_id"),
            "dag_id": obj.get("dag_id"),
            "run_id": obj.get("run_id"),
            "dag_display_name": obj.get("dag_display_name"),
            "task_display_name": obj.get("task_display_name"),
            "run_after": obj.get("run_after"),
            "value": obj.get("value")
        })
        return _obj


